###
POST  http://localhost:3003/login
Content-Type: application/json

{
     "email": "jana@gmail.com",
     "password": "1"
}

###
POST http://localhost:3003/teste
Content-Type: application/json

{
     "user": "luiz",
     "pwd": "123"
}

###
POST http://localhost:3003/login
Content-Type: application/json

{
     "email": "jana@gmail.com",
     "password": "1"
}


###
GET  http://localhost:3003/teste HTTP/1.1
Content-Type: application/xml
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIyNTk5NjUxLCJleHAiOjE2MjI1OTk5NTF9.6JuFGApc3jZbxsKP4D8EEWQrdfGuXNVZDITjrw1N9cE

###
GET  http://localhost:3003/post/all 


###
GET  http://localhost:3003/post/2 

###
PUT  http://localhost:3003/post/create 
Content-Type: application/json

{
     "userId": 1, 
     "text": "Teste", 
     "price": 200
}